{
  "route": {
    "receiver": "local-drill",
    "group_by": [
      "alertname",
      "application"
    ],
    "group_wait": "10s",
    "group_interval": "1m",
    "repeat_interval": "4h"
  },
  "receivers": [
    {
      "name": "local-drill",
      "webhook_configs": [
        {
          "url": "http://alert-receiver:8080/alerts",
          "send_resolved": true
        }
      ]
    }
  ]
}
