{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "resources.json"
  ],
  "configMapGenerator": [
    {
      "name": "operations-monitoring",
      "files": [
        "prometheus.yml",
        "alerts.yml",
        "alertmanager.yml",
        "alert-receiver.py"
      ]
    }
  ]
}
