import React,{useEffect,useState,useRef} from 'react';
import {api,money} from '../api';
import {Form} from './Forms';
import {Tickets} from './SupportPage';
const productFields=[{name:'sku',label:'SKU',pattern:'[A-Za-z0-9_-]+',maxLength:64},{name:'name',label:'Product name',maxLength:150},{name:'description',label:'Description',type:'textarea',required:false},{name:'price',label:'Price INR',type:'number',min:0.01,step:0.01},{name:'stockQuantity',label:'Available stock',type:'number',min:0,max:1000000},{name:'category',label:'Category',required:false},{name:'imageUrl',label:'HTTPS image URL',type:'url',required:false},{name:'active',label:'Visibility',options:[{value:'true',label:'Visible'},{value:'false',label:'Hidden'}]}];
const productBody=b=>({...b,price:Number(b.price),stockQuantity:Number(b.stockQuantity),active:String(b.active)==='true',imageUrl:b.imageUrl||null});
export default function AdminDashboard({action,busy}){
  const [tab,setTab]=useState('analytics');const [page,setPage]=useState(0);const [data,setData]=useState(null);const [editing,setEditing]=useState(null);const [variant,setVariant]=useState(null);const [stock,setStock]=useState(null);const [history,setHistory]=useState(null);const [days,setDays]=useState(30);const [threshold,setThreshold]=useState(5);
  const currentKey=useRef('');currentKey.current=tab+':'+page+':'+days+':'+threshold;
  async function load(){
    const key=tab+':'+page+':'+days+':'+threshold;
    const path={products:`/api/v1/products/admin/catalog?page=${page}`,orders:`/api/admin/orders?page=${page}`,coupons:`/api/admin/coupons?page=${page}`,inventory:`/api/v1/products/admin/low-stock?page=${page}&threshold=${threshold}`,delivery:'/api/admin/delivery',analytics:`/api/admin/analytics?days=${days}`}[tab];
    if(path){const response=await api(path);if(key===currentKey.current)setData(response);}
  }
  useEffect(()=>{setData(null);action(load);},[tab,page,days,threshold]);
  function change(t){setData(null);setTab(t);setPage(0);setEditing(null);setVariant(null);setStock(null);setHistory(null);}
  async function mutate(path,method,body){await api(path,{method,body});await load();}
  return <section className="feature-page admin-dashboard"><div className="section-heading"><div className="eyebrow">STORE MANAGEMENT</div><h2>Admin dashboard</h2><p>Manage your catalog, orders and customer experience.</p></div><div className="tabs admin-tabs">{['analytics','products','inventory','orders','coupons','delivery','support'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>change(t)}>{t}</button>)}</div>
    {tab==='support'?<Tickets admin action={action} busy={busy}/>:<><button disabled={busy} onClick={()=>action(load)}>Refresh</button>{!data&&<p>{busy?'Loading…':'Could not load data. Refresh to retry.'}</p>}
    {tab==='analytics'&&<><label className="inline-field">Reporting period<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,365].map(n=><option key={n} value={n}>{n} days</option>)}</select></label>{data&&<><div className="metric-grid">{[['Orders',data.orderCount],['Booked sales',money(data.bookedSales)],['Net collected revenue',money(data.collectedRevenue)],['Refunded',money(data.refunds)],['Cancelled / expired / failed',data.cancelledOrders],['Cancellation rate',`${data.cancellationRate.toFixed(1)}%`]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="muted">Booked sales include confirmed through delivered orders. Net collected revenue includes paid online orders and collected COD payments after completed refunds. Reports use orders created in the selected period. Daily grouping uses UTC.</p><h3>Popular products</h3><div className="table-wrap"><table><thead><tr><th>Product</th><th>Units</th><th>Merchandise value</th></tr></thead><tbody>{data.popular.map(p=><tr key={p.productId}><td>{p.name}</td><td>{p.units}</td><td>{money(p.merchandiseValue)}</td></tr>)}</tbody></table></div><h3>Daily booked sales</h3><div className="sales-chart">{data.daily.map(d=><div key={d.date}><span>{d.date}</span><progress aria-label={`Sales on ${d.date}`} max={Math.max(1,...data.daily.map(r=>Number(r.sales)))} value={Number(d.sales)}/><strong>{money(d.sales)}</strong></div>)}</div><h3>Order statuses</h3><div className="row-actions">{Object.entries(data.statuses).map(([name,count])=><span className="badge" key={name}>{name}: {count}</span>)}</div></>}</>}
    {tab==='products'&&<><h3>{editing?'Edit product':'Create product'}</h3><Form key={editing?.id||'new'} fields={productFields} initial={editing?{...editing,active:String(editing.active)}:{active:'true'}} busy={busy} onSubmit={b=>action(async()=>{await mutate(editing?`/api/v1/products/${editing.id}`:'/api/v1/products',editing?'PUT':'POST',productBody(b));setEditing(null);})}/>{editing&&<button onClick={()=>setEditing(null)}>Cancel editing</button>}{data?.content?.map(p=><article className="order-card" key={p.id}><div className="order-heading"><strong>{p.name}</strong><span>{p.sku}</span><span>{money(p.price)} · {p.stockQuantity} in stock · {p.active?'Visible':'Hidden'}</span></div><div className="row-actions"><button onClick={()=>{setEditing(p);setVariant(null);}}>Edit</button><button onClick={()=>{setVariant(p);setEditing(null);}}>Create variant</button><button disabled={busy} onClick={()=>action(()=>mutate(`/api/v1/products/${p.id}`,'PUT',productBody({...p,active:!p.active})))}>{p.active?'Hide':'Show'}</button><button disabled={busy} onClick={()=>action(()=>mutate(`/api/v1/products/${p.id}`,'DELETE'))}>Delete product</button></div></article>)}{variant&&<><h3>New variant for {variant.name}</h3><p className="muted">Variants have their own SKU, product ID, price and available stock.</p><Form key={variant.id} fields={[{name:'label',label:'Variant label',maxLength:100},{name:'size',label:'Size or model',required:false,maxLength:50},{name:'color',label:'Color',required:false,maxLength:50},...productFields]} initial={{name:variant.name,description:variant.description,price:variant.price,category:variant.category,active:'true',stockQuantity:0}} busy={busy} onSubmit={b=>action(async()=>{const {label,size,color,...product}=b;await mutate(`/api/v1/products/admin/${variant.id}/variants`,'POST',{label,size,color,product:productBody(product)});setVariant(null);})}/><button onClick={()=>setVariant(null)}>Cancel variant</button></>}</>}
    {tab==='inventory'&&<><label className="inline-field">Low stock threshold<input type="number" min="0" max="1000000" value={threshold} onChange={e=>setThreshold(Math.max(0,Math.min(1000000,Number(e.target.value))))}/></label><p className="muted">Alerts show active products at or below the threshold. Use Products to adjust any other SKU.</p>{data?.content?.map(p=><article className="order-card" key={p.id}><strong>{p.name} · {p.sku}</strong><p>{p.stockQuantity} available</p><div className="row-actions"><button onClick={()=>setStock(p)}>Replenish or adjust</button><button disabled={busy} onClick={()=>action(async()=>{setHistory({product:p,movements:await api(`/api/v1/products/admin/${p.id}/movements`)});})}>Stock history</button></div></article>)}<Form fields={[{name:'productId',label:'Product ID',type:'number',min:1},{name:'delta',label:'Stock change',type:'number',min:-1000000,max:1000000},{name:'reference',label:'Supplier or adjustment reference',maxLength:150}]} initial={{productId:stock?.id,delta:10}} key={stock?.id||'adjust'} busy={busy} submit="Record stock adjustment" onSubmit={b=>action(()=>mutate(`/api/v1/products/admin/${b.productId}/stock`,'POST',{delta:Number(b.delta),reference:b.reference}))}/>{history&&<><h3>{history.product.name} stock history</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Change</th><th>Remaining</th><th>Reason</th><th>Reference</th></tr></thead><tbody>{history.movements.content.map(m=><tr key={m.id}><td>{new Date(m.createdAt).toLocaleString()}</td><td>{m.delta}</td><td>{m.resultingQuantity}</td><td>{m.reason}</td><td>{m.reference}</td></tr>)}</tbody></table></div>{history.movements.totalPages>1&&<div className="pagination"><button disabled={history.movements.first||busy} onClick={()=>action(async()=>setHistory({...history,movements:await api(`/api/v1/products/admin/${history.product.id}/movements?page=${history.movements.number-1}`)}))}>Previous</button><button disabled={history.movements.last||busy} onClick={()=>action(async()=>setHistory({...history,movements:await api(`/api/v1/products/admin/${history.product.id}/movements?page=${history.movements.number+1}`)}))}>Next</button></div>}</>}</>}
    {tab==='orders'&&data?.content?.map(o=><AdminOrder key={o.id} order={o} action={action} busy={busy} mutate={mutate}/>)}
    {tab==='coupons'&&<><h3>Create coupon</h3><Form fields={[{name:'code',label:'Code',pattern:'[A-Za-z0-9_-]{3,40}'},{name:'type',label:'Discount type',options:['PERCENT','FIXED']},{name:'value',label:'Discount amount',type:'number',min:0.01,step:0.01},{name:'minimumSpend',label:'Minimum spend INR',type:'number',min:0,step:0.01,defaultValue:0},{name:'expiresAt',label:'Expiry',type:'datetime-local'},{name:'usageLimit',label:'Usage limit',type:'number',min:1,max:1000000,defaultValue:100}]} busy={busy} onSubmit={b=>action(()=>mutate('/api/admin/coupons','POST',{...b,value:Number(b.value),minimumSpend:Number(b.minimumSpend),usageLimit:Number(b.usageLimit),expiresAt:new Date(b.expiresAt).toISOString()}))}/>{data?.content?.map(c=><article className="order-card" key={c.code}><strong>{c.code}</strong><p>{c.type} {c.value} · Used {c.usedCount}/{c.usageLimit} · Expires {new Date(c.expiresAt).toLocaleString()}</p><button disabled={busy} onClick={()=>action(()=>mutate(`/api/admin/coupons/${c.code}`,'PATCH',{active:!c.active}))}>{c.active?'Deactivate':'Activate'}</button></article>)}</>}
    {tab==='delivery'&&<><h3>Postal code delivery rules</h3><p className="muted">The longest matching prefix wins. Unmatched postal codes use free delivery with a 5–7 day estimate. These are store estimates, not carrier promises.</p><Form fields={[{name:'postalPrefix',label:'Postal prefix',pattern:'[0-9]{1,6}'},{name:'fee',label:'Delivery fee INR',type:'number',min:0,step:0.01},{name:'freeAbove',label:'Free delivery above merchandise subtotal INR',type:'number',min:0,step:0.01},{name:'minDays',label:'Minimum days',type:'number',min:1,max:60},{name:'maxDays',label:'Maximum days',type:'number',min:1,max:90},{name:'active',label:'Rule state',options:[{value:'true',label:'Active'},{value:'false',label:'Disabled'}]}]} busy={busy} onSubmit={b=>action(()=>mutate('/api/admin/delivery','PUT',{...b,fee:Number(b.fee),freeAbove:Number(b.freeAbove),minDays:Number(b.minDays),maxDays:Number(b.maxDays),active:b.active==='true'}))}/>{Array.isArray(data)&&data.map(r=><article key={r.postalPrefix} className="order-card"><strong>Prefix {r.postalPrefix}</strong><p>{money(r.fee)} · Free above {money(r.freeAbove)} · {r.minDays}–{r.maxDays} days · {r.active?'Active':'Disabled'}</p><button disabled={busy} onClick={()=>action(()=>mutate('/api/admin/delivery','PUT',{...r,active:!r.active}))}>{r.active?'Disable':'Enable'}</button></article>)}</>}
    {data?.totalPages>1&&<div className="pagination"><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {data.totalPages}</span><button disabled={page+1>=data.totalPages||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}
  </section>;
}
function AdminOrder({order:o,action,busy,mutate}){
  const next={CONFIRMED:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'}[o.status];
  return <article className="order-card"><div className="order-heading"><strong>{o.id}</strong><span className="badge">{o.status}</span><strong>{money(o.totalPrice)}</strong></div><p>{o.paymentMethod} · {o.paymentStatus} · {new Date(o.createdAt).toLocaleString()}</p>{o.items.map(i=><p key={i.productId}>{i.name} × {i.quantity}</p>)}{o.shippingAddress&&<p>Ship to {o.shippingAddress.line1}, {o.shippingAddress.city}, {o.shippingAddress.postalCode}</p>}{next&&<Form submit={`Mark ${next.toLowerCase()}`} busy={busy} fields={next==='SHIPPED'?[{name:'carrier',label:'Carrier',maxLength:100},{name:'trackingNumber',label:'Tracking number',maxLength:150}]:next==='DELIVERED'&&o.paymentMethod==='CASH_ON_DELIVERY'?[{name:'cashCollected',label:'Cash collection',options:[{value:'false',label:'Not collected'},{value:'true',label:'Collected'}]}]:[]} onSubmit={b=>action(()=>mutate(`/api/admin/orders/${o.id}/status`,'PATCH',{...b,status:next,cashCollected:b.cashCollected==='true'}))}/>}
    {o.returnRequest?.status==='REQUESTED'&&<Form submit="Record return decision" busy={busy} fields={[{name:'decision',label:'Decision',options:['APPROVED','REJECTED']},{name:'note',label:'Decision note',type:'textarea',maxLength:1000}]} onSubmit={b=>action(()=>mutate(`/api/admin/orders/${o.id}/return`,'PATCH',b))}/>}
    {o.returnRequest?.status==='APPROVED'&&<Form submit="Confirm physical return receipt" busy={busy} fields={[{name:'restock',label:'Stock decision',options:[{value:'true',label:'Restock all items'},{value:'false',label:'Discard all returned items'}]}]} onSubmit={b=>action(()=>mutate(`/api/admin/orders/${o.id}/return/receive`,'POST',{restock:b.restock==='true'}))}/>}
    {o.refund?.status==='MANUAL_REQUIRED'&&<Form submit="Record completed COD refund" busy={busy} fields={[{name:'reference',label:'External refund reference',maxLength:150}]} onSubmit={b=>action(()=>mutate(`/api/admin/orders/${o.id}/refund/manual`,'POST',b))}/>}
    {o.refund?.status==='FAILED'&&<button disabled={busy} onClick={()=>action(()=>mutate(`/api/admin/orders/${o.id}/refund/retry`,'POST'))}>Retry failed refund</button>}
    {o.returnRequest&&o.returnRequest.status!=='NONE'&&<p>Return: {o.returnRequest.status} · {o.returnRequest.reason}</p>}
  </article>;
}
