import React,{useEffect,useState} from 'react';
import {api,money} from '../api';
import {Form} from './Forms';
export function ProductExtras({product,onSelect,session,action,busy}){
  const [variants,setVariants]=useState([]);const [reviews,setReviews]=useState(null);const [page,setPage]=useState(0);
  useEffect(()=>{let live=true;setReviews(null);action(async()=>{const [v,r]=await Promise.all([api(`/api/v1/products/${product.id}/variants`),api(`/api/reviews/products/${product.id}?page=${page}`)]);if(live){setVariants(v);setReviews(r);}});return()=>{live=false;};},[product.id,page]);
  return <><h3>Choose a variant</h3>{variants.length?<div className="row-actions">{variants.map(v=><button disabled={busy} key={v.id} onClick={()=>onSelect(v.product)}>{v.label} {v.size} {v.color} · {money(v.product.price)} {v.product.stockQuantity<1?'· Sold out':''}</button>)}</div>:<p className="muted">This product has no additional variants.</p>}
    <button disabled={busy} onClick={()=>action(async()=>{if(!session)throw new Error('Sign in to save favourites');await api(`/api/wishlist/${product.id}`,{method:'PUT'});})}>Save to wishlist</button>
    <h3>Verified reviews</h3>{reviews&&<><p>{reviews.averageRating.toFixed(1)} / 5 · {reviews.reviewCount} reviews</p>{reviews.reviews.content.map(r=><article className="review" key={r.id}><strong>{r.rating} / 5 · Verified purchase</strong><p>{r.comment}</p><small>{new Date(r.createdAt).toLocaleDateString()}</small></article>)}<div className="pagination"><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={!reviews.reviews.totalPages||page+1>=reviews.reviews.totalPages||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}</>;
}
export function Wishlist({action,busy,onAdd,onSelect}){
  const [products,setProducts]=useState([]);const [page,setPage]=useState(0);const [pages,setPages]=useState(0);
  async function load(){const list=await api(`/api/wishlist?page=${page}`);const results=await Promise.allSettled(list.content.map(i=>api(`/api/v1/products/${i.productId}`)));setProducts(results.map((r,i)=>r.status==='fulfilled'?r.value:{id:list.content[i].productId,name:'Unavailable product',unavailable:true}));setPages(list.totalPages);}
  useEffect(()=>{action(load);},[page]);
  return <section className="feature-page"><h2>Your wishlist</h2>{!products.length&&<p>No saved products yet.</p>}<div className="product-grid">{products.map(p=><article className="order-card" key={p.id}><h3>{p.name}</h3>{!p.unavailable&&<><p>{money(p.price)}</p><button onClick={()=>onSelect(p)}>View product</button><button disabled={busy||p.stockQuantity<1} onClick={()=>onAdd(p)}>Add to bag</button></>}<button disabled={busy} onClick={()=>action(async()=>{await api(`/api/wishlist/${p.id}`,{method:'DELETE'});await load();})}>Remove saved item</button></article>)}</div><div className="pagination"><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.max(1,pages)}</span><button disabled={page+1>=pages||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>;
}
export function OrderExtras({order,action,busy,onRefresh,onPay,onSupport}){
  const [panel,setPanel]=useState('');
  return <><div className="order-summary"><span>Merchandise {money(order.subtotal)}</span><span>Discount −{money(order.discount)}</span><span>Delivery {money(order.deliveryFee)}</span>{order.deliveryMinDays&&<span>Delivery estimate {order.deliveryMinDays}–{order.deliveryMaxDays} days from order confirmation</span>}</div><div className="row-actions">{order.checkout&&<button disabled={busy} onClick={()=>onPay(order)}>Pay online</button>}{order.deliveredAt&&<button onClick={()=>setPanel(panel==='review'?'':'review')}>Review a purchase</button>}{order.deliveredAt&&(!order.returnRequest||order.returnRequest.status==='NONE')&&<button onClick={()=>setPanel(panel==='return'?'':'return')}>Request full-order return</button>}<button onClick={()=>onSupport(order)}>Get order support</button></div>
    {order.returnRequest?.status!=='NONE'&&order.returnRequest?.status&&<p>Return: {order.returnRequest.status} · {order.returnRequest.decisionNote||order.returnRequest.reason}</p>}{order.refund&&order.refund.status!=='NONE'&&<p>Refund: {order.refund.status}</p>}
    {panel==='review'&&<Form busy={busy} submit="Publish review" fields={[{name:'productId',label:'Purchased product',options:order.items.map(i=>({value:i.productId,label:i.name}))},{name:'rating',label:'Rating',options:['5','4','3','2','1']},{name:'comment',label:'Your review',type:'textarea'}]} onSubmit={body=>action(async()=>{await api(`/api/orders/${order.id}/reviews`,{method:'POST',body:{...body,productId:Number(body.productId),rating:Number(body.rating)}});setPanel('');})}/>}
    {panel==='return'&&<><p className="muted">Returns cover all items and must be requested within 30 days of delivery. Approval and receipt are required before refunding.</p><Form busy={busy} submit="Request return" fields={[{name:'reason',label:'Reason',type:'textarea',maxLength:1000}]} onSubmit={body=>action(async()=>{await api(`/api/orders/${order.id}/returns`,{method:'POST',body});setPanel('');await onRefresh();})}/></>}</>;
}
