import React,{useEffect,useState} from 'react';
import {api} from '../api';
import {Form} from './Forms';
export function Tickets({admin=false,action,busy,orderId=''}){
  const [tickets,setTickets]=useState([]);const [page,setPage]=useState(0);const [pages,setPages]=useState(0);
  async function load(){const data=await api(`${admin?'/api/admin/support':'/api/support'}?page=${page}`);setTickets(data.content);setPages(data.totalPages);}
  useEffect(()=>{action(load);},[page,admin]);
  return <><h2>{admin?'Customer support':'Help and support'}</h2>{!admin&&<><p>Delivery estimates appear at checkout. For an order issue, include its order number or open support from My orders.</p><Form busy={busy} submit="Create support ticket" initial={{orderId}} fields={[{name:'orderId',label:'Order ID (optional)',required:false},{name:'subject',label:'Subject',maxLength:150},{name:'message',label:'How can we help?',type:'textarea'}]} onSubmit={body=>action(async()=>{await api('/api/support',{method:'POST',body:{...body,orderId:body.orderId||null}});await load();})}/></>}{tickets.map(t=><article className="order-card" key={t.id}><div className="order-heading"><strong>{t.subject}</strong><span className="badge">{t.status}</span></div><p>Ticket {t.id.slice(0,8)} {t.orderId&&`· Order ${t.orderId}`}</p>{t.messages.map((m,i)=><div className={`ticket-message ${m.admin?'staff':''}`} key={i}><strong>{m.admin?'Store support':'Customer'}</strong><p>{m.text}</p><small>{new Date(m.createdAt).toLocaleString()}</small></div>)}<Form busy={busy} submit="Send reply" fields={[{name:'message',label:'Reply',type:'textarea'}]} onSubmit={body=>action(async()=>{await api(`/api/support/${t.id}/messages`,{method:'POST',body});await load();})}/>{admin&&<div className="row-actions">{['OPEN','IN_PROGRESS','RESOLVED'].map(status=><button key={status} disabled={busy||status===t.status} onClick={()=>action(async()=>{await api(`/api/admin/support/${t.id}`,{method:'PATCH',body:{status}});await load();})}>{status}</button>)}</div>}</article>)}<div className="pagination"><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.max(pages,1)}</span><button disabled={page+1>=pages||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></>;
}
export default function SupportPage(props){return <section className="feature-page"><Tickets {...props}/></section>;}
