-- Baseline of the application schema. Do not edit after deployment.
create table coupons (active bit not null, discount_value decimal(19,2) not null, minimum_spend decimal(19,2) not null, usage_limit integer not null, used_count integer not null, expires_at datetime(6) not null, version bigint, code varchar(40) not null, type varchar(255) not null, primary key (code)) engine=InnoDB;
create table order_event_outbox (created_at datetime(6) not null, id bigint not null auto_increment, published_at datetime(6), trace_parent varchar(256), trace_state varchar(512), event_id varchar(255) not null, order_id varchar(255) not null, payload longtext not null, primary key (id)) engine=InnoDB;
create table order_shipments (created_at datetime(6), next_track_at datetime(6), tracked_at datetime(6), version bigint, fingerprint varchar(64) not null, pickup_fingerprint varchar(64), awb varchar(255), carrier varchar(255), failure varchar(255), id varchar(255) not null, order_id varchar(255) not null, pickup_status varchar(255), provider_order_id varchar(255), shipment_id varchar(255), status varchar(255), tracking_status varchar(255), direction enum ('FORWARD','RETURN') not null, mode enum ('LIVE','MOCK','STAGING') not null, provider enum ('DELHIVERY','SHIPROCKET') not null, primary key (id)) engine=InnoDB;
create table product_reviews (rating integer not null, created_at datetime(6), id bigint not null auto_increment, product_id bigint not null, user_id bigint not null, comment varchar(2000), order_id varchar(255) not null, primary key (id)) engine=InnoDB;
create table purchase_orders (cart_cleanup_done bit not null, cart_cleared bit not null, coupon_redeemed boolean default false, discount decimal(19,2), inventory_committed boolean default false, payment_creation_attempted bit not null, provider_shipment_requested boolean default false, return_restock bit, stock_released boolean default false, subtotal decimal(19,2), total decimal(19,2), address_id bigint not null, cart_version bigint not null, created_at datetime(6) not null, delivered_at datetime(6), event_sequence bigint default 0, expires_at datetime(6), return_received_at datetime(6), return_requested_at datetime(6), shipped_at datetime(6), updated_at datetime(6), user_id bigint not null, version bigint, coupon_code varchar(40), key_hash varchar(64) not null, manual_refund_reference varchar(150), return_decision_note varchar(1000), return_reason varchar(1000), carrier varchar(255), closure_reason varchar(255), currency varchar(255) not null, failure_reason varchar(255), id varchar(255) not null, payment_method varchar(255) not null, payment_status varchar(255) not null, razorpay_order_id varchar(255), razorpay_payment_id varchar(255), razorpay_refund_id varchar(255), refund_attempt_id varchar(255), refund_failure varchar(255), refund_status varchar(255), return_status varchar(255), status varchar(255) not null, tracking_number varchar(255), address_json longtext not null, cart_json longtext not null, items_json longtext, primary key (id)) engine=InnoDB;
create table wishlist_entries (created_at datetime(6), id bigint not null auto_increment, product_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create index IDX86btb1iflxndi08e20h8arqxs on order_event_outbox (published_at, id);
alter table order_event_outbox add constraint UKdw2vtwrluak1qm6xwqp6ceicb unique (event_id);
alter table order_shipments add constraint UK26vi0ygaq2618n4vtbplc7xdb unique (order_id, direction);
alter table product_reviews add constraint UKmqb1fao7o48so0929ybsl23ja unique (user_id, product_id);
alter table purchase_orders add constraint UKqt0jkjybpfh6xkof5nrlxtvyv unique (user_id, key_hash);
alter table purchase_orders add constraint UKbsehy4y6ximbi6n5n0klcahjd unique (user_id, cart_version);
alter table purchase_orders add constraint UK8dfkrx6spw8mi6bwasslishy7 unique (razorpay_order_id);
alter table purchase_orders add constraint UK54vaajmnxh5a62qftc00ucm5c unique (razorpay_payment_id);
alter table wishlist_entries add constraint UKnujrsrc7v20j0updf6n7fhs8h unique (user_id, product_id);
