{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "ecommerce",
  "resources": [
    "../base",
    "resources.json"
  ],
  "configMapGenerator": [
    {
      "name": "observability-config",
      "files": [
        "tempo.yaml"
      ]
    }
  ],
  "generatorOptions": {
    "disableNameSuffixHash": true
  }
}
