{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "ecommerce",
  "resources": [
    "resources-0.json",
    "resources-6.json",
    "resources-12.json",
    "resources-18.json",
    "resources-24.json",
    "resources-30.json"
  ]
}