"""Source-checked examples for the ecommerce technical handbook."""
from copy import deepcopy
T = '2026-09-15T10:00:00Z'
OID = '11111111-1111-4111-8111-111111111111'
USER = dict(id=1, name='Asha Sharma', email='asha@example.com', phone='+919876543210', gender=None, dob=None, profileImage=None, memberSince=T, roles=['ROLE_USER'])
AUTH = dict(accessToken='<ACCESS_TOKEN>', refreshToken='<REFRESH_TOKEN>', user=USER)
ADDR_REQ = dict(line1='10 Example Road', line2='Apartment 2', city='Pune', state='Maharashtra', postalCode='411001', country='India')
ADDR = dict(createdDate=T, updatedDate=T, createdBy=None, updatedBy=None, id=1, **ADDR_REQ, defaultAddress=True)
PREF = dict(id=1, language='en', currency='INR', darkMode=False, emailNotifications=True, smsNotifications=True, whatsAppNotifications=False, pushNotifications=True, communicationPreference='EMAIL')
PROD_REQ = dict(sku='PHONE-001', name='Everyday Phone', description='A sample catalog product', price=1000.00, stockQuantity=10, category='Electronics', active=True, imageUrl='https://example.com/phone.jpg')
PROD = dict(id=1, **PROD_REQ, createdAt=T, updatedAt=T)
ITEM = dict(productId=1, name='Everyday Phone', price=1000.00, quantity=2)
CART = dict(userId=1, items=[dict(productId=1, name='Everyday Phone', quantity=2, unitPrice=1000.00, subtotal=2000.00, available=True)], totalQuantity=2, totalPrice=2000.00, version=3)
EMPTY_CART = dict(userId=1, items=[], totalQuantity=0, totalPrice=0, version=4)
RET = dict(status='NONE', reason=None, decisionNote=None, requestedAt=None, receivedAt=None, restock=None, manualRefundReference=None)
ORDER = dict(id=OID, status='CONFIRMED', paymentMethod='CASH_ON_DELIVERY', paymentStatus='UNPAID', items=[ITEM], totalPrice=1800.00, currency='INR', shippingAddress=ADDR, cartCleared=True, failureReason=None, checkout=None, createdAt=T, expiresAt=None, refund=dict(status='NONE', razorpayRefundId=None, failure=None), carrier=None, trackingNumber=None, shippedAt=None, deliveredAt=None, subtotal=2000.00, discount=200.00, couponCode='SAVE10', returnRequest=RET)
COUPON_REQ = dict(code='SAVE10', type='PERCENT', value=10.00, minimumSpend=500.00, expiresAt='2027-12-31T23:59:59Z', usageLimit=100)
COUPON = dict(**COUPON_REQ, usedCount=1, active=True, version=1)
WISH = dict(id=1, userId=1, productId=1, createdAt=T)
REVIEW = dict(id=1, rating=5, comment='Useful for everyday work.', createdAt=T, verifiedPurchase=True)
NOTICE = dict(eventId='22222222-2222-4222-8222-222222222222', userId=1, orderId=OID, eventSequence=1, type='OrderConfirmed', message='Your order is confirmed.', occurredAt=T, receivedAt=T)

def page(item, size=20, sort=False):
    return dict(content=[item], pageable=dict(pageNumber=0, pageSize=size, sort=dict(sorted=sort, unsorted=not sort, empty=not sort), offset=0, paged=True, unpaged=False), last=True, totalPages=1, totalElements=1, size=size, number=0, sort=dict(sorted=sort, unsorted=not sort, empty=not sort), first=True, numberOfElements=1, empty=False)

def order(**changes):
    result = deepcopy(ORDER); result.update(changes); return result

APIS = []
def add(group, name, method, route, request, response, status=200, access='Bearer access token', rules='', errors='', source='', aliases=None, headers=None):
    APIS.append(dict(group=group, name=name, method=method, route=route, request=request, response=response, status=status, access=access, rules=rules, errors=errors, source=source, aliases=aliases or [], headers=headers or {}))

add('User service', 'Register a customer', 'POST', '/api/users/register', dict(name='Asha Sharma',email='asha@example.com',phone='+919876543210',password='ExamplePass123!'), USER, 201, 'Public',
    'name is nonblank and at most 100 characters; email is nonblank and syntactically valid; phone permits an optional plus and 7 to 15 digits; password is 8 to 100 characters. Email is trimmed and lowercased. Both email and phone must be unique. BCrypt hashes the password; ROLE_USER and default preferences are created. A six digit verification OTP is persisted and user events are published. No password or OTP is returned.',
    '400 duplicate email or phone or validation error; 409 database uniqueness conflict. No admin role is accepted from the request.', 'UserController.register and UserService.register')
add('User service','Sign in','POST','/api/auth/login',dict(email='asha@example.com',password='ExamplePass123!'),AUTH,access='Public',
    rules='UserService checks lock expiry and active status before BCrypt comparison. Failed attempts and login history are committed even when ApiException is thrown. The fifth wrong password locks the account for 30 minutes. Success resets failures, records device from User-Agent and remote IP, and returns a 15 minute default JWT plus a 7 day opaque refresh token.',errors='400 invalid credentials, missing user, locked or inactive account; field validation errors also reject malformed requests.',source='AuthController.login and UserService.login',aliases=['POST /auth/login'])
add('User service','Rotate a refresh token','POST','/api/auth/refresh',dict(refreshToken='<REFRESH_TOKEN>'),AUTH,access='Public endpoint requiring the refresh token in its body',rules='Reject missing, revoked, expired tokens and inactive or non-ACTIVE users. Revoke the old refresh row and create a new token with the same device. The access JWT is newly signed. The code does not lock this row or implement token family reuse detection, so concurrent refreshes are a known hardening gap.',errors='400 invalid, expired or revoked refresh token; 400 inactive account.',source='AuthController.refresh and UserService.refresh',aliases=['POST /auth/refresh'])
add('User service','Request password reset','POST','/api/auth/forgot-password',dict(email='asha@example.com'),None,202,'Public',
    'Persist a six digit secure random OTP with a ten minute expiry and publish PasswordResetOtpRequested. The OTP is not in the HTTP response or event payload. Email delivery is not implemented. The method looks up the user and therefore does reveal a missing email through a 400 error.', '400 unknown or malformed email.', 'AuthController.forgot and UserService.forgot', aliases=['POST /auth/forgot-password','POST /forgot-password'])
add('User service','Reset a password using OTP','POST','/api/auth/reset-password',dict(email='asha@example.com',otp='123456',newPassword='AnotherPass123!'),None,204,'Public',
    'Find the latest unused token matching user and supplied OTP. Reject expired tokens, mark the selected token used, hash the new password, record passwordChangedOn and revoke all refresh tokens. A stored OTP is required; the sample is a placeholder, not a working bypass. Existing access JWTs are not revoked by this operation.', '400 invalid OTP, expired OTP, unknown email or password validation failure.', 'AuthController.reset and UserService.reset', aliases=['POST /auth/reset-password'])
add('User service','Verify an email address','POST','/api/auth/verify-email',dict(email='asha@example.com',otp='123456'),None,204,'Public',
    'Locate the latest matching unused verification OTP, check its ten minute expiry, mark it used and set emailVerified=true. The current login method does not require this flag; verification is stored account metadata, not a login gate.', '400 invalid or expired OTP or missing user.', 'AuthController.verify and UserService.verify', aliases=['POST /auth/verify-email'])
add('User service','Sign out the supplied session','POST','/api/auth/logout',None,None,204, rules='X-Refresh-Token identifies the refresh row to revoke. The token must belong to the authenticated email; missing or foreign rows have no effect and still complete. Clearing the browser storage is separate. A still-valid access token remains cryptographically usable until expiry.',errors='401 missing authentication; missing required X-Refresh-Token is rejected by request binding.',source='SessionController.logout and UserService.logout',headers={'X-Refresh-Token':'<REFRESH_TOKEN>'})
add('User service','Sign out all refresh sessions','POST','/api/auth/logout-all',None,None,204,rules='Revoke every refresh token for the authenticated user. This is not an access-token denylist and does not immediately log out other services holding unexpired JWTs.',errors='401 unauthenticated; 400 user not found.',source='SessionController.logoutAll and UserService.logoutAll')
add('User service','Read your profile','GET','/api/users/me',None,USER,rules='Resolve identity from the JWT email subject, not a userId query parameter. UserResponse intentionally omits the password and internal account security fields.',errors='401 unauthenticated; 400 user not found.',source='UserController.me and UserService.me')
add('User service','Read a profile by identifier','GET','/api/users/1',None,USER,rules='Path template is /api/users/{id}. IMPORTANT CURRENT BEHAVIOR: any authenticated user can call this endpoint for another ID. Neither ownership nor ROLE_ADMIN is checked. The response includes email and phone; restrict or remove this endpoint before public production use.',errors='401 unauthenticated; 400 user not found.',source='UserController.get and UserService.get')
updated_user = dict(USER,name='Asha S',dob='1998-05-17',gender='Female')
add('User service','Update your profile','PUT','/api/users/me',dict(name='Asha S',phone='+919876543210',dob='1998-05-17',gender='Female'),updated_user,rules='name and phone are required. A changed phone must be unique; name is at most 100 characters and phone follows the registration digit pattern. dob is an ISO date and gender has no enumerated validation. Null optional values overwrite prior values. Email and roles cannot be updated here.',errors='400 invalid phone, duplicate phone or missing user.',source='UserController.update and UserService.update',aliases=['PUT /api/users/profile'])
add('User service','Change your password','PUT','/api/users/change-password',dict(oldPassword='ExamplePass123!',newPassword='AnotherPass123!'),None,204,rules='Require the old password to match BCrypt. The new password must contain 8 to 100 characters; update the hash and passwordChangedOn. Unlike the reset flow, this method does not revoke refresh tokens. Neither password-change time nor active status is checked by downstream JWT filters.',errors='400 incorrect old password or validation failure; 401 unauthenticated.',source='UserController.password and UserService.changePassword')
add('User service','Delete your account','DELETE','/api/users/me',None,None,204,rules='Soft delete: active=false and status=DELETED, revoke refresh tokens and publish AccountDeletedEvent. User rows and historical orders are retained. Existing signed access tokens are not checked against this flag by every service.',errors='401 unauthenticated; 400 user not found.',source='UserController.delete and UserService.delete')
add('User service','Delete your account by identifier','DELETE','/api/users/1',None,None,204,rules='Path template is /api/users/{id}. Compare the requested ID to the authenticated profile ID before soft deletion. Even an admin token cannot use this endpoint to delete somebody else.',errors='400 You can only delete your own account; 401 unauthenticated.',source='UserController.deleteById')
add('User service','List your addresses','GET','/api/addresses',None,[ADDR],rules='Resolve user by JWT email and return only their addresses, default first and ID descending. The entity serializes inherited audit fields; @JsonIgnore prevents serialization of its User relationship.',errors='401 unauthenticated; 400 user not found.',source='AddressController.list and AccountSettingsService.addresses')
add('User service','Add an address','POST','/api/addresses',ADDR_REQ,ADDR,201,rules='line1, city, state, postalCode and country are nonblank; line2 is optional. The first stored address is marked default. No request field can select an owner. An AddressAddedEvent is published. No country-specific postal validation is implemented.',errors='400 required address fields missing; 401 unauthenticated.',source='AddressController.add and AccountSettingsService.add')
add('User service','Update an address','PUT','/api/addresses/1',dict(ADDR_REQ,line1='20 Example Road'),dict(ADDR,line1='20 Example Road'),rules='Path template is /api/addresses/{id}. The service finds the address, compares its owner to the authenticated user, then replaces address fields. The default flag is not changed through this request.',errors='400 Address not found for missing or foreign address; validation errors; 401 unauthenticated.',source='AddressController.update and AccountSettingsService.update')
add('User service','Remove an address','DELETE','/api/addresses/1',None,None,204,rules='Delete only an owned address. Previously created orders keep their copied addressJson. Deleting the default address does not automatically choose another default.',errors='400 Address not found for missing or foreign address; 401 unauthenticated.',source='AddressController.delete and AccountSettingsService.delete')
add('User service','Set a default address','PATCH','/api/addresses/1/default',None,ADDR,rules='Verify ownership. If already default, return immediately. Otherwise clear that user’s existing default flags and set this address default. Concurrent requests are not protected by a database unique-default constraint or explicit user lock.',errors='400 Address not found; 401 unauthenticated.',source='AddressController.defaultAddress and AccountSettingsService.makeDefault')
add('User service','Read preferences','GET','/api/users/preferences',None,PREF,rules='Return the authenticated user’s preference row. If absent, the GET creates a default row; this is an intentional implementation detail to mention when discussing HTTP safe methods. Currency preference does not change order currency, which remains INR.',errors='401 unauthenticated; 400 user not found.',source='PreferencesController.get and AccountSettingsService.preferences')
add('User service','Update preferences','PUT','/api/users/preferences',dict(language='en',currency='INR',darkMode=True,emailNotifications=True,smsNotifications=False,whatsAppNotifications=False,pushNotifications=True,communicationPreference='EMAIL'),dict(PREF,darkMode=True,smsNotifications=False),rules='Only non-null request fields are applied, so this PUT behaves as a partial update. There is no @Valid or enum validation on this controller request. Flags store preferences; they do not configure an SMS/email provider or control the current notification consumer.',errors='401 unauthenticated; malformed JSON rejected by binding.',source='PreferencesController.update and AccountSettingsService.updatePreferences')
add('User service','Direct service greeting','GET','/hello',None,'User Service is running...',access='Public on user-service port 8082',rules='A plain text greeting, not a dependency readiness check. No explicit gateway route exists for /hello. Do not infer MySQL, Kafka or payment health from this response.',errors='No custom business failure path.',source='HealthController.hello')

add('Product service','Search the public catalog','GET','/api/v1/products?query=phone&category=Electronics&minPrice=100&maxPrice=2000&inStock=true&page=0&size=20&sort=price,asc',None,page(PROD,sort=True),access='Public',rules='All filters are optional and combined with AND. Name search and category match are case-insensitive; search is a contains LIKE query and literal %, _ and backslash are escaped. Category is an exact match. Price bounds are inclusive and nonnegative. inStock=true means quantity > 0; false means quantity = 0. Hidden products are always excluded, including for admin callers of this public listing. Default page size is 20 and sort createdAt ascending. Size is capped at 100. Sort permits id, name, price, createdAt and stockQuantity; id is appended as a stable tie-breaker.',errors='400 negative/inverted price range or unsupported sort; invalid bearer tokens are rejected even on public routes.',source='ProductController.getProducts and ProductSearch.search')
add('Product service','Read a product','GET','/api/v1/products/1',None,PROD,access='Public for active products; ROLE_ADMIN can view inactive products',rules='Fetch current JPA version from MySQL, then optionally load the versioned Redis entry. ProductController hides inactive products from non-admin callers with 404. The service method itself can still return inactive products for internal Java use.',errors='404 missing or hidden product; 401 invalid supplied bearer token.',source='ProductController.getProduct and ProductServiceImpl.getProduct')
add('Product service','Create a product','POST','/api/v1/products',PROD_REQ,PROD,201,'Bearer token with ROLE_ADMIN',rules='SKU is nonblank, at most 64 characters, letters/digits/underscore/hyphen, normalized to uppercase and unique. Name is nonblank and <=150; description <=2000; price is strictly positive with at most 17 integer and 2 fractional digits. Stock is required, 0 to 1000000. Category <=100; active defaults true when null. imageUrl is optional, <=2048 and empty or HTTPS. The response has a Location header pointing to the created product.',errors='401 missing or invalid token; 403 non-admin; 400 validation; 409 duplicate SKU.',source='ProductController.createProduct and ProductServiceImpl.createProduct')
add('Product service','Replace product details','PUT','/api/v1/products/1',dict(PROD_REQ,stockQuantity=8),dict(PROD,stockQuantity=8),access='Bearer token with ROLE_ADMIN',rules='Same validation as creation. Exclude the current ID when checking duplicate SKU. The stock value sets currently available stock, not original purchased quantity. @Version detects overlapping writes at transaction time; the API does not require an ETag from a long-open admin form.',errors='404 missing; 409 duplicate SKU or optimistic conflict; 400 validation; 401/403 access control.',source='ProductController.updateProduct and ProductServiceImpl.updateProduct')
add('Product service','Delete an unreserved product','DELETE','/api/v1/products/1',None,None,204,'Bearer token with ROLE_ADMIN',rules='Lock the product row. Reject deletion when a RESERVED or COMMITTED reservation contains it, so existing checkout and return restocking retain their product. Deactivate through PUT instead. A product whose reservations were released or returned can be deleted.',errors='409 reserved or fulfilled stock; 404 missing; 401/403 access control.',source='ProductServiceImpl.deleteProduct and ReservationRepository.hasReservation')
add('Product service','List the admin catalog','GET','/api/v1/products/admin/catalog?page=0&size=20',None,page(PROD,sort=True),access='Bearer token with ROLE_ADMIN',rules='List active and inactive products. This endpoint accepts Pageable parameters; it does not expose the public search filters. It uses the same size cap, sort allowlist and id tie-breaker.',errors='401/403; 400 invalid sort.',source='ProductController.adminCatalog and ProductSecurityConfig')

add('Cart service','Read your cart','GET','/api/cart',None,CART,rules='Load cart by authenticated numeric userId. Read current product details for each line; calculate subtotal and total with BigDecimal. Missing or hidden products remain removable as unavailable lines with null prices, excluded from totals. An absent cart returns an empty response with version null. version distinguishes later purchases of identical contents.',errors='401; 503 product dependency failure; missing product lines do not fail the complete response.',source='CartController.get and CartService.get')
add('Cart service','Add quantity to your cart','POST','/api/cart/items',dict(productId=1,quantity=2),CART,rules='Both values are required and positive. Quantity is added to the existing amount. Validate the combined quantity against current active product stock and integer range. Persist/flush the cart and return the complete calculated cart. This POST is not generally idempotent; do not automatically replay after an unknown outcome.',errors='400 invalid quantity; 404 product missing; 409 insufficient stock or concurrent cart conflict; 503 product unavailable.',source='CartController.add and CartService.add')
add('Cart service','Set a cart line quantity','PUT','/api/cart/items/1',dict(quantity=2),CART,rules='Replace rather than increment quantity. The item must already exist in this user’s cart. Required positive quantity is checked against current stock. @Version on Cart and a unique user/product element collection entry protect persistence; concurrency failures are surfaced as 409.',errors='404 cart item missing; 409 insufficient stock or concurrency; 400 validation; 503 dependency failure.',source='CartController.update and CartService.update')
add('Cart service','Remove one cart line','DELETE','/api/cart/items/1',None,None,204,rules='Remove only from the authenticated cart; missing cart or missing line is a no-op. The operation does not reserve or release inventory because cart additions never reserved stock.',errors='401; concurrent modification can produce 409.',source='CartController.remove and CartService.remove')
add('Cart service','Empty your cart','DELETE','/api/cart',None,None,204,rules='Clear the authenticated cart item collection. Missing cart is a no-op. The cart entity remains and its version changes when an existing item collection changes.',errors='401; concurrent modification can produce 409.',source='CartController.clear and CartService.clear')

add('Order service','Create or resume checkout','POST','/api/orders',dict(addressId=1,paymentMethod='CASH_ON_DELIVERY',couponCode='SAVE10'),ORDER,headers={'Idempotency-Key':'checkout-demo-0001'},rules='addressId must be positive; paymentMethod is CASH_ON_DELIVERY or RAZORPAY. Optional couponCode is 3 to 40 ASCII letters/digits/underscore/hyphen. The required key is 8 to 128 characters from that same character set. Customer identity, cart contents, product prices and shipping address ownership are resolved server-side. The key is hashed and unique per user. The same key must keep address, payment method and normalized coupon unchanged. A second key cannot buy the same cart version. COD confirms after reservation; online setup may remain pending. Response includes Location: /api/orders/{id}.',errors='200 known usable state; 202 CREATING, RESERVED or CANCELLING; 409 FAILED, changed key details, duplicate cart version or invalid coupon; 404 foreign address; 503 dependencies or missing test payment configuration.',source='OrderController.create and OrderService.create')
add('Order service','List your orders','GET','/api/orders?page=0&size=20',None,page(ORDER),rules='Only the authenticated user’s orders, newest first. page >=0 and size 1 to 100, default 20. GET reads persisted state; it does not itself call advance or force payment reconciliation.',errors='401; invalid page/size rejected.',source='OrderController.list and OrderService.list')
add('Order service','Read an owned order','GET',f'/api/orders/{OID}',None,ORDER,rules='UUID path parameter. A missing or foreign order returns the same 404. Snapshot fields preserve the prices, discount and address captured at purchase; they are not replaced when catalog/profile data changes.',errors='404 missing or foreign order; 400 malformed UUID; 401.',source='OrderController.get and OrderService.owned')
add('Order service','Cancel an eligible order','POST',f'/api/orders/{OID}/cancel',None,order(status='CANCELLED'),rules='Allow CREATING, RESERVED, PENDING_PAYMENT, CONFIRMED or PROCESSING. Record CANCELLING first, then release reservation, finalize CANCELLED and release coupon use. Paid online orders request a refund. Closed/FAILED states return idempotently; shipped/delivered orders require the return flow instead.',errors='202 while cancelling; 409 invalid transition; 404 foreign or missing order; 401.',source='OrderController.cancel and OrderLifecycle.cancel')
add('Order service','Verify a Razorpay browser callback','POST',f'/api/orders/{OID}/payments/verify',dict(razorpay_order_id='order_demo1',razorpay_payment_id='pay_demo1',razorpay_signature='<64_HEX_CHARACTERS>'),order(paymentMethod='RAZORPAY',paymentStatus='PAID',expiresAt='2026-09-15T10:15:00Z'),rules='Provider order and payment IDs must match order_ and pay_ alphanumeric formats; signature must contain 64 hex characters. Use the stored provider order ID for HMAC, not an arbitrary browser ID. Fetch provider payment and provider order, require captured/refunded payment with exact order, amount and INR, and a paid order. Late captures keep a closed order closed and request refund.',errors='400 bad signature or payment/order mismatch; 409 not captured or conflicting payment; 404 foreign order; 503 provider issue.',source='OrderController.verify and OrderService.verify')
add('Order service','Receive a signed payment webhook','POST','/api/payments/razorpay/webhook',dict(event='payment.captured',payload=dict(payment=dict(entity=dict(id='pay_demo1',order_id='order_demo1')))),None,204,'Raw-body HMAC in X-Razorpay-Signature instead of customer JWT',
    'Verify exact raw bytes before parsing JSON. Accept payment.captured, order.paid, refund.created, refund.processed and refund.failed. Other events are acknowledged without action. Unknown provider orders are ignored. Re-query provider state instead of trusting event amount or a browser success flag. A minimal consumed-fields sample is shown; real Razorpay envelopes have additional fields.',
    '400 invalid signature or JSON; 503 missing webhook secret or surfaced provider error. Payment advance catches recoverable failures, so a 204 can mean scheduled recovery will finish the work.', 'PaymentWebhookController.webhook and OrderService.webhook',headers={'X-Razorpay-Signature':'<HMAC_SHA256_OF_EXACT_BODY>'})
add('Order service','List orders as an administrator','GET','/api/admin/orders?page=0&size=20',None,page(ORDER,sort=True),access='Bearer token with ROLE_ADMIN',rules='Return all orders, newest first. page >=0, size 1 to 100. The current OrderView does not include userId, although its copied delivery address is visible to admins.',errors='401/403; invalid page or size.',source='AdminOrderController.list and OrderService.adminList')
add('Order service','Read any order as an administrator','GET',f'/api/admin/orders/{OID}',None,ORDER,access='Bearer token with ROLE_ADMIN',rules='UUID validation and ROLE_ADMIN at the controller class. This route intentionally does not apply customer ownership filtering.',errors='401/403; 404 missing order; 400 invalid UUID.',source='AdminOrderController.get and OrderService.adminGet')
add('Order service','Advance order fulfillment','PATCH',f'/api/admin/orders/{OID}/status',dict(status='SHIPPED',carrier='Example Courier',trackingNumber='TRACK001'),order(status='SHIPPED',carrier='Example Courier',trackingNumber='TRACK001',shippedAt=T),access='Bearer token with ROLE_ADMIN',rules='Allowed target enum: PROCESSING, SHIPPED, DELIVERED. Preconditions are CONFIRMED, PROCESSING and SHIPPED respectively. Online orders must be PAID. SHIPPED requires nonblank carrier <=100 and trackingNumber <=150. DELIVERED COD requires cashCollected=true. Repeating a shipping transition with different carrier/tracking is 409. Shipping/delivery triggers inventory commit; the state update can already be persisted if that remote commit fails, so retry/refresh is necessary.',errors='409 invalid transition, unpaid online order or changed shipping details; 400 missing shipment fields or COD confirmation; 401/403; 404 missing.',source='AdminOrderController.fulfill and OrderLifecycle.fulfill')
add('Order service','Retry a failed online refund','POST',f'/api/admin/orders/{OID}/refund/retry',None,order(status='CANCELLED',paymentMethod='RAZORPAY',paymentStatus='REFUND_PENDING',refund=dict(status='PENDING',razorpayRefundId='rfnd_demo1',failure=None)),access='Bearer token with ROLE_ADMIN',rules='Require a closed order with refundStatus FAILED. If a provider refund ID exists, first read it. Create a new attempt only after the previous provider refund is confirmed failed. Uncertain calls reuse the existing attempt UUID and identical request body. A retry response can remain PENDING.',errors='409 nonfailed/nonclosed refund; 503 provider failure; 401/403; 404 missing order.',source='AdminOrderController.retryRefund and OrderLifecycle.retryRefund')

add('Reviews and wishlist','Read public product reviews','GET','/api/reviews/products/1?page=0&size=10',None,dict(averageRating=5.0,reviewCount=1,reviews=page(REVIEW,size=10)),access='Public GET',rules='Positive product ID, page >=0 and size 1 to 100; default size 10. Return aggregate average and count plus newest-first reviews. Customer and order IDs are omitted from ReviewView. The service does not validate that the product still exists; an unknown product ID can return an empty collection with average zero.',errors='400 invalid parameters; supplied invalid JWT can produce 401.',source='ShoppingController.reviews and ShoppingService.reviews')
add('Reviews and wishlist','Review a delivered purchase','POST',f'/api/orders/{OID}/reviews',dict(productId=1,rating=5,comment='Useful for everyday work.'),REVIEW,201,rules='Positive product ID; rating 1 to 5; nonblank comment <=2000. Lock and verify order ownership. Require deliveredAt and the product in itemsJson. Enforce one review per user/product through an existence check plus database uniqueness. A returned order with a delivery timestamp remains reviewable. No edit/delete/moderation endpoint is implemented.',errors='404 foreign order; 409 not delivered or duplicate review; 400 nonpurchased product or invalid rating/comment.',source='ShoppingController.review and ShoppingService.review')
add('Reviews and wishlist','Read saved products','GET','/api/wishlist?page=0&size=20',None,page(WISH),rules='Only own wishlist entries, newest first. Entries contain product IDs, not catalog snapshots. The browser fetches each product; missing/hidden saved products can still be removed. page >=0; size 1 to 100.',errors='401; invalid pagination.',source='ShoppingController.wishlist and ShoppingService.wishlist')
add('Reviews and wishlist','Save a product','PUT','/api/wishlist/1',None,WISH,rules='Positive path ID. Return existing own entry before checking the product again, making sequential repeats safe. New entries require an active product via product-service. The unique user/product constraint prevents duplicates; simultaneous first inserts may return a 409 to one caller.',errors='404 missing/inactive product; 503 product service unavailable; 409 concurrent uniqueness conflict; 401.',source='ShoppingController.save and ShoppingService.save')
add('Reviews and wishlist','Remove a saved product','DELETE','/api/wishlist/1',None,None,204,rules='Delete by authenticated user and product ID; absent entries are harmless. The browser moves an item to the bag through separate cart read/add and wishlist delete calls.',errors='401; positive path validation.',source='ShoppingController.remove and ShoppingService.remove')

add('Coupons','Estimate a coupon discount','POST','/api/coupons/quote',dict(code='SAVE10',subtotal=2000.00),dict(code='SAVE10',subtotal=2000.00,discount=200.00,total=1800.00),rules='Code 3 to 40 allowed characters; subtotal >=0.01 with at most 14 integer and 2 fractional digits. Validate active flag, expiry, usage and minimum spend. This caller-supplied amount is only an estimate and never authorizes the paid amount. No usage is consumed by a quote.',errors='409 unknown, inactive, expired, exhausted or minimum-spend failure; 400 validation; 401.',source='CouponController.quote and CouponService.quote')
add('Coupons','Create a discount rule','POST','/api/admin/coupons',COUPON_REQ,dict(COUPON,usedCount=0,version=0),access='Bearer token with ROLE_ADMIN',rules='type PERCENT or FIXED; positive value with <=12 integer/2 fractional digits; nonnegative minimumSpend with same digit limits; expiry must be future; usageLimit 1 to 1000000. Percent cannot exceed 100. Normalize code uppercase and reject existing code. Current controller returns 200, not 201. Rule values cannot be edited through another endpoint.',errors='400 invalid rule; 409 duplicate code; 401/403.',source='CouponController.create and CouponService.create')
add('Coupons','List discount rules','GET','/api/admin/coupons?page=0&size=20',None,page(COUPON,sort=True),access='Bearer token with ROLE_ADMIN',rules='All rules, including inactive/expired ones, ordered by expiry descending. Includes usedCount and JPA version. page >=0; size 1 to 100.',errors='401/403; invalid pagination.',source='CouponController.list and CouponService.list')
add('Coupons','Activate or deactivate a rule','PATCH','/api/admin/coupons/SAVE10',dict(active=False),dict(COUPON,active=False,version=2),access='Bearer token with ROLE_ADMIN',rules='Require a non-null Boolean active. Lock the coupon row before changing it. Activating an already expired code does not extend its expiry; validation still rejects it. Existing order price snapshots are unchanged.',errors='409 unknown coupon; 400 null active; 401/403.',source='CouponController.active and CouponService.setActive')

return_requested = dict(RET,status='REQUESTED',reason='The item is damaged',requestedAt=T)
return_approved = dict(return_requested,status='APPROVED',decisionNote='Return all items for inspection')
return_received = dict(return_approved,status='RECEIVED',receivedAt=T,restock=False)
add('Returns','Request a full order return','POST',f'/api/orders/{OID}/returns',dict(reason='The item is damaged'),order(status='DELIVERED',paymentStatus='COLLECTED',deliveredAt=T,returnRequest=return_requested),rules='Owned order, nonblank reason <=1000, status DELIVERED, and deliveredAt no more than 30 days ago. One full-order request is stored. A repeat with the same trimmed reason is idempotent; a different reason conflicts. The order remains DELIVERED during request/approval; no stock or money is moved yet.',errors='404 foreign or missing order; 409 outside window/not delivered/different repeat; 400 validation; 401.',source='ReturnController.request and OrderLifecycle.requestReturn')
add('Returns','Approve or reject a return','PATCH',f'/api/admin/orders/{OID}/return',dict(decision='APPROVED',note='Return all items for inspection'),order(status='DELIVERED',paymentStatus='COLLECTED',deliveredAt=T,returnRequest=return_approved),access='Bearer token with ROLE_ADMIN',rules='decision is APPROVED or REJECTED; nonblank note <=1000. Only REQUESTED can change. Identical decision and trimmed note are idempotent. A rejection cannot later be received or changed to approval via this endpoint.',errors='409 not REQUESTED or changed repeat; 400 validation; 401/403; 404 missing.',source='ReturnController.decide and OrderLifecycle.decideReturn')
add('Returns','Record receipt and inventory disposition','POST',f'/api/admin/orders/{OID}/return/receive',dict(restock=False),order(status='RETURNED',paymentStatus='REFUND_PENDING',deliveredAt=T,refund=dict(status='MANUAL_REQUIRED',razorpayRefundId=None,failure=None),returnRequest=return_received),access='Bearer token with ROLE_ADMIN',rules='Require explicit restock Boolean and APPROVED return. Commit RETURN_RECEIVING with the decision before a remote call. Product-service either restocks all quantities or marks them discarded. Then mark RETURNED/RECEIVED and start refund handling. Online uses Razorpay; COD waits for an external manual refund. During outage the API can return 200 with RETURN_RECEIVING because advance defers recovery; 200 alone does not prove physical receipt processing is complete.',errors='409 unapproved or changed receipt decision; 400 null restock; 401/403. Recovery handles temporary inventory failure.',source='ReturnController.receive and OrderLifecycle.startReceiveReturn receiveReturn')
add('Returns','Record a completed COD refund','POST',f'/api/admin/orders/{OID}/refund/manual',dict(reference='BANK-REFUND-001'),order(status='RETURNED',paymentStatus='REFUNDED',deliveredAt=T,refund=dict(status='PROCESSED',razorpayRefundId=None,failure=None),returnRequest=dict(return_received,manualRefundReference='BANK-REFUND-001')),access='Bearer token with ROLE_ADMIN',rules='Nonblank reference <=150. Require RETURNED, CASH_ON_DELIVERY and MANUAL_REQUIRED. Mark the already externally paid refund processed. A repeat with the same trimmed reference succeeds. This endpoint neither transfers money nor independently verifies a bank payment; the admin attestation is trusted.',errors='409 wrong state/method or changed processed reference; 400 validation; 401/403.',source='ReturnController.manual and OrderLifecycle.manualRefund')

add('Notification service','Read your notification inbox','GET','/api/notifications?page=0&size=20',None,page(NOTICE),rules='Filter by authenticated numeric user ID, newest receivedAt first. page >=0, size 1 to 100. Each notification is stored once by eventId. This API does not mark items read or delete them. Received order and return events drive the inbox; user-events are a separate stream.',errors='401 invalid/missing JWT; invalid pagination.',source='NotificationController.list and NotificationRepository')

add('Internal APIs','Fetch a checkout cart snapshot','GET','/internal/carts/1',None,dict(userId=1,version=3,items={'1':2}),access='X-Service-Key on cart-service port 8084',rules='Path template /internal/carts/{userId}. No explicit public gateway route. Return only stable quantities and JPA version, not client prices. Missing/empty cart returns 409. JSON object keys are strings even though the Java map uses Long.',errors='401 wrong/missing service key; 409 empty cart.',source='CheckoutCartController.snapshot')
add('Internal APIs','Consume only a matching cart version','POST','/internal/carts/1/consume',dict(version=3),dict(cleared=True),access='X-Service-Key on cart-service port 8084',rules='Lock the cart. Clear only when cart exists and a non-null requested version equals the current version. Missing/stale/null version returns 200 {"cleared":false}; preserve items added after checkout. A repeated successful consumption can return false after the version changed, so effect idempotency does not mean identical response bytes.',errors='401 wrong/missing key; malformed JSON binding failure.',source='CheckoutCartController.consume')
add('Internal APIs','Reserve stock for an order','PUT',f'/internal/inventory/reservations/{OID}',dict(userId=1,items={'1':2}),dict(id=OID,state='RESERVED',items=[ITEM]),access='X-Service-Key on product-service port 8083',rules='UUID order ID; positive userId; nonempty map with <=100 entries; positive IDs and quantities. Existing reservation must match user and quantities and still be RESERVED. For a new reservation lock products in ascending ID order, require active/enough stock, snapshot prices/names and subtract stock in one local transaction. Any invalid line rolls back all deductions.',errors='422 product missing/inactive/insufficient; 409 different or already released reservation; 400 validation; 401 key.',source='InventoryController.reserve and InventoryService.reserve')
add('Internal APIs','Release reserved stock','DELETE',f'/internal/inventory/reservations/{OID}',None,None,204,'X-Service-Key on product-service port 8083',
    'A repeated RELEASED reservation is a no-op. Unknown order IDs create a released tombstone so a delayed reserve cannot recreate stock demand after cancellation. RESERVED quantities are restored with overflow checking. COMMITTED and returned states cannot be released.', '409 committed/returned or missing reserved product or integer overflow; 401 key.', 'InventoryController.release and InventoryService.release')
add('Internal APIs','Commit shipped inventory','POST',f'/internal/inventory/reservations/{OID}/commit',None,None,204,'X-Service-Key on product-service port 8083',
    'A reservation must exist and not be RELEASED. Mark COMMITTED so cancellation cannot restore stock already shipped. Repeats are safe; returned states are preserved rather than rewritten to COMMITTED.', '404 unknown reservation; 409 released reservation; 401 key.', 'InventoryController.commit and InventoryService.commit')
add('Internal APIs','Apply the return stock decision','POST',f'/internal/inventory/reservations/{OID}/return',dict(restock=True),None,204,'X-Service-Key on product-service port 8083',
    'Explicit restock Boolean. RESERVED or COMMITTED can transition to RETURNED (add quantities once) or RETURNED_DISCARDED (no addition). Same target repeats are no-ops. Opposite disposition conflicts. Product rows are locked in sorted order; missing products and overflow fail. This endpoint trusts the internal caller to have enforced delivered-order approval and receipt; it cannot verify orderdb itself.', '404 unknown reservation; 409 released/already returned differently/missing restock product/overflow; 400 null restock; 401 key.', 'InventoryController.receiveReturn and InventoryService.receiveReturn')


